### ISSUE TITLE
list_plugins method drops the modules with same name from different plugin directory

### ISSUE THREAD

**Issue by xingheng** [mitsuhiko/pluginbase#17]
The modules with same names in different plugin directory won't be returned in `list_plugins`.

Here is my case, I have a plugins directory structure like this,

```
plugins
├── __init__.py
├── builtin
│   ├── __init__.py
│   ├── logger
│   │   ├── __init__.py
│       ├── setup.py
│   │   └── logger.py
├── device
│   ├── __init__.py
│   ├── setup.py
```

### Expect
The `list_plugins` returns all the module names including those with the same name and could be `load_plugin` correctly.
`['logger', 'setup', 'setup']`

### Actual
The `list_plugins` returns all the unique names only and could be `load_plugin` correctly.
`['logger', 'setup']`

### Code
```
plugin_base = PluginBase(package='app.plugins',
                            searchpath=[get_path('plugins/builtin')])

source = plugin_base.make_plugin_source(
    searchpath=[get_path('./plugins/%s/' % name)],
    identifier=self.name)
print source.list_plugins()
```

**Comment by zeroSteiner** [comment]
So if there are two modules with the same name, in this case `setup`, I don't understand why they would both need to be listed when only one could be loaded as a plugin. The one that's found first in the path would be loaded, while the other wouldn't be touched.

I'm guessing in your use case you have a bunch of plugins which all have a `setup.py` which is your entry point? If that's the case what I'd recommend doing is using `./plugins` as your source and then loading `'%s.setup' % name`.

**Comment by xingheng** [comment]
The `setup.py` is my plugins' entry point exactly, the suggested `'%s.setup' % name` plugin name couldn't be loaded with error `raise ImportError('Plugin names cannot contain dots.')`.

https://github.com/mitsuhiko/pluginbase/blob/c7a9b74bb7185879f45c0c61679a58483adec7d9/pluginbase.py#L299

```
self.source = plugin_base.make_plugin_source(
    searchpath=[get_path('./plugins')],
    identifier=self.name)

print self.source.list_plugins()
try:
    plugin = self.source.load_plugin('%s.setup' % self.name)
    plugin.setup(self)
except AttributeError as e:
    pass
```

Did I miss something? @zeroSteiner

**Comment by xingheng** [comment]
gotcha!

I use the `./plugins` as the search paths and `self.name` as plugin name (in my case, that's `device`, etc), then import the `setup` function to my plugin package/module with `from setup import setup` in `device/__init__.py`.

Thanks! @zeroSteiner
