### ISSUE TITLE
KeyError warning when sys.modules is empty as PluginSource.cleanup is called

### ISSUE THREAD

**Issue by htoothrot** [mitsuhiko/pluginbase#6]
Not sure of the exact cause yet, but running the following source on python 3.4:

```
from pluginbase import PluginBase
a_base = PluginBase('some')
a_source = a_base.make_plugin_source(searchpath=['.'])

import asyncio

@asyncio.coroutine
def what():
    return
```
results in the following warning being displayed:
```
Exception ignored in: <bound method PluginSource.__del__ of <pluginbase.PluginSource object at 0x021F0AF0>>
Traceback (most recent call last):
  File "d:\python34\lib\site-packages\pluginbase.py", line 247, in __del__
  File "d:\python34\lib\site-packages\pluginbase.py", line 303, in cleanup
  File "d:\python34\lib\site-packages\pluginbase.py", line 319, in __cleanup
KeyError: ('pluginbase._internalspace._spf57aab93650650e4c1433e9cb9bd5a38',)
```

Could potentially be fixed by adding a default `None` to the `_sys.modules.pop()` call causing the `KeyError`.

**Comment by Vesuvium** [comment]
I'm having the same issue.  Plugins are loaded and executed fine. 

```
from pluginbase import PluginBase


class Plugins():
    def __init__(self):
        self.plugin_base = PluginBase(package='App.plugins')
        self.plugin_source = self.plugin_base.make_plugin_source(searchpath=['../plugins/'])

    def setup(self):
        for name in self.plugin_source.list_plugins():
            plugin = self.plugin_source.load_plugin(name)
            plugin.setup(self)

if __name__ == '__main__':
    plugins = Plugins()
    plugins.setup()
```

```
Exception ignored in: <bound method PluginSource.__del__ of <pluginbase.PluginSource object at 0x1067a30f0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pluginbase.py", line 247, in __del__
  File "/usr/local/lib/python3.4/site-packages/pluginbase.py", line 303, in cleanup
  File "/usr/local/lib/python3.4/site-packages/pluginbase.py", line 319, in __cleanup
KeyError: ('pluginbase._internalspace._sp052aa2cfe42d5873f09200ae6bca4df2',)
```

**Comment by ueg1990** [comment]
Was anyone able to fix this issue?

**Comment by htoothrot** [comment]
@ueg1990 

As I noted in original issue changing https://github.com/mitsuhiko/pluginbase/blob/master/pluginbase.py#L319 to:
`_sys.modules.pop(modname, None)`

...will avoid a KeyError.

A cause may be hinted at here: https://github.com/mitsuhiko/pluginbase/blob/master/pluginbase.py#L306

**Comment by ueg1990** [comment]
Hello @htoothrot, I did follow your suggestion and making that change did avoid the KeyError. But since this issue has not been fixed, any advice on how I can use this project in my project? I am not sure if I can just fork and clone the project, add my change and then pip install that in my project.

**Comment by zeroSteiner** [comment]
I also ran into this issue and submitted pull request #11 in an attempt to resolve it.

**Comment by zeroSteiner** [comment]
This issue has now been resolved. The `__cleanup` method checks to ensure that the key exists prior to removing it from `_sys.modules`.
